services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: noderegistry
      POSTGRES_PASSWORD: noderegistry
      POSTGRES_DB: noderegistry
    ports:
      - "5432:5432"

  grpc-server:
    build:
      context: .
      dockerfile: grpc_server/Dockerfile
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: postgresql://noderegistry:noderegistry@db:5432/noderegistry
    depends_on:
      - db

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      GRPC_SERVER: grpc-server:50051
    depends_on:
      - grpc-server